name: env2
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/r  # Keep if you need R packages

dependencies:
  - python=3.10 # Or your preferred Python version (e.g., 3.9, 3.10)
  - pip
  - asttokens
  - certifi
  - comm
  - debugpy
  - decorator
  - exceptiongroup
  - executing
  - ipykernel
  - ipython
  - jedi
  - jupyter_client
  - jupyter_core
  - matplotlib-inline
  - parso
  - pexpect
  - pickleshare
  - platformdirs
  - psutil
  - ptyprocess
  - pure_eval
  - pyzmq
  - stack_data
  - traitlets
  - typing_extensions
  - wcwidth
  - zipp
  




  - pip:
      - alembic==1.14.1
      - altair==5.3.0
      - amqp==5.2.0
      - aniso8601==9.0.1
      - annotated-types==0.6.0
      - anyio==4.3.0
      - appdirs==1.4.4
      - attrs==23.2.0
      - audioread==3.0.1
      - bcrypt==4.0.1
      - beautifulsoup4==4.12.3
      - billiard==4.2.0
      - bleach==6.2.0
      - blinker==1.8.2
      - bs4==0.0.2
      - cachetools==5.3.3
      - celery==5.4.0
      - cffi==1.16.0
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - checksumdir==1.2.0
      - click==8.1.7
      - click-didyoumean==0.3.1
      - click-plugins==1.1.1
      - click-repl==0.3.0
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - contourpy==1.2.1
      - curl-cffi==0.7.0b4
      - cycler==0.12.1
      - databricks-sdk==0.44.0
      - defusedxml==0.7.1
      - deprecated==1.2.18
      - deprecation==2.1.0
      - distro==1.9.0
      - dnspython==2.6.1
      - docker==7.1.0
      - docstring-parser==0.16
      - duckdb==0.10.2
      - duckduckgo-search==5.3.1
      - email-validator==2.2.0
      - exa-py==1.0.9
      - fastjsonschema==2.21.1
      - filelock==3.16.1
      - flask==3.0.3
      - flask-excel==0.0.7
      - flask-jwt-extended==4.6.0
      - flask-login==0.6.3
      - flask-migrate==4.1.0
      - flask-principal==0.4.0
      - flask-restful==0.3.10
      - flask-security-too==5.4.3
      - flask-sqlalchemy==3.1.1
      - flask-wtf==1.2.1
      - fonttools==4.51.0
      - fpdf==1.7.2
      - frozendict==2.4.4
      - fsspec==2024.12.0
      - gdown==5.2.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-api-core==2.24.0
      - google-auth==2.37.0
      - google-cloud-aiplatform==1.77.0
      - google-cloud-bigquery==3.27.0
      - google-cloud-core==2.4.1
      - google-cloud-resource-manager==1.14.0
      - google-cloud-storage==2.19.0
      - google-crc32c==1.6.0
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.66.0
      - graphene==3.4.3
      - graphql-core==3.2.6
      - graphql-relay==3.2.0
      - greenlet==3.0.3
      - grpc-google-iam-v1==0.14.0
      - grpcio==1.69.0
      - grpcio-status==1.69.0
      - gunicorn==23.0.0
      - h11==0.14.0
      - html5lib==1.1
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.27.1
      - idna==3.7
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.0
      - itsdangerous==2.2.0
      - jinja2==3.1.4
      - jiter==0.8.2
      - joblib==1.4.2
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyterlab-pygments==0.3.0
      - kiwisolver==1.4.5
      - kombu==5.4.0
      - lancedb==0.19.0
      - lazy-loader==0.4
      - librosa==0.10.2.post1
      - llvmlite==0.44.0
      - lml==0.1.0
      - lxml==5.2.1
      - mako==1.3.8
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.8.4
      - mdurl==0.1.2
      - mistune==3.1.1
      - mlflow==2.20.1
      - mlflow-skinny==2.20.1
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multitasking==0.0.11
      - narwhals==1.22.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - numba==0.61.0
      - numpy==2.0.1
      - openai==1.59.8
      - opentelemetry-api==1.30.0
      - opentelemetry-sdk==1.30.0
      - opentelemetry-semantic-conventions==0.51b0
      - orjson==3.10.3
      - overrides==7.7.0
      - packaging==24.0
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - passlib==1.7.4
      - peewee==3.17.5
      - pgvector==0.2.5
      - phidata==2.7.10
      - pillow
      - phi